### PR TITLE
Added more methods

### PR DESCRIPTION
**Pull request by felipehertzer**
Hey, thanks for you project, I added more methods.

### CODE REVIEW

**Comment by rogervila** [comment]
Amazing @felipehertzer, thank you very much for your contributions!

**Comment by rogervila** [comment]
Let me first fix the SonarCloud integration. Then I will request you @felipehertzer to update your branch.

**Comment by felipehertzer** [comment]
@rogervila no worries, let me know.

**Comment by rogervila** [comment]
@felipehertzer merge main into your branch to get the Sonarcloud integration fix.

**Comment by felipehertzer** [comment]
Hey @rogervila done! I will work in more functions and fixes, may we can check if worth we use camelCase or move to snake_case. Also if we should fix the name functions to the exact same name of the carbon functions in PHP. Thanks

**Comment by rogervila** [comment]
> Hey @rogervila done! I will work on more functions and fixes, may we can check if worth we use camelCase or move to snake_case. Also if we should fix the name functions to the exact same name of the carbon functions in PHP. Thanks

Thank you very much.

Yes, snake_case is the python way to go for methods. 

I used camel case because the first idea was to mimic as much as possible the original PHP Carbon library, but since Python and PHP are different, I think it does not make sense now that the library is implemented.

If you consider it worth it, we can move it to snake_case 

Anyway, I am releasing 0.2.0 with your current changes :)

**Pull request merged**
